### PR TITLE
Build for Nodejs projects as a  baseline

### PR DESCRIPTION
**Pull request by woksin**

### CODE REVIEW

**Comment by woksin** [comment]
Depend on whether or not the stuff you're working on, @einari, should depend on the upcoming Javascript.Build.Client repo or this one. Is it a package for client or node applications?

**Comment by einari** [comment]
I'll see how it all fits together. What I have solved is basically be able to run in Electron mode - which means browser, with being able to import files - both local and from other packages. It deserves a writeup on its own. Pretty hairy stuff. But in pure Node mode - this won't be necessary as we can just transpire module handling into CommonJS - Node and we're good. What I probably need to do however, is make it simple to build layers of types of build and be able to add and override quite easily.

**Comment by woksin** [comment]
We should perhaps have our own 'dolittle build' script thing where we can do these things and make it simple to do these common npm things

**Comment by einari** [comment]
That would be very interesting. Build and run tests and all.  Great idea!   
This is especially interesting with transpilation as well when you have repositories with multiple packages and a workspace like I've done the for JavaScript.Fundamentals project. 
And of course VSCode support as well.

**Comment by woksin** [comment]
Yeah, flexible tools for building, trnaspiling and running js apps.

Look at aurellias build for example https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge?files=1

**Comment by woksin** [comment]
We can give the end user options, for example transpile to cjs, UMD, AMD... And more

**Comment by einari** [comment]
Yup..  We should do them all. 
You might find the pre-cursor to the new Dolittle stuff interesting; I did the following a couple of years ago: https://github.com/Cratis/JavaScript.Pipeline

**Pull request merged**
